import type { Sql } from 'postgres';
import { requireGeneratorEnabled, requireGeneratorMain } from './generator.js';
import type { ComputeNotificationV3 } from '@tka/database';
import { fail } from './validation.js';

export async function generatorHttp(path: string, notification?: ComputeNotificationV3) {
  const base = process.env.NUMORA_GENERATOR_URL,
    token = process.env.NUMORA_GENERATOR_TOKEN;
  if (!base || !token || token.length < 32) fail('GENERATOR_NOT_CONFIGURED', 503);
  const url = new URL(base);
  if (
    url.username ||
    url.password ||
    (url.protocol !== 'https:' &&
      !(url.protocol === 'http:' && ['localhost', '127.0.0.1'].includes(url.hostname)))
  )
    fail('GENERATOR_URL_INVALID', 503);
  const response = await fetch(new URL(path, url), {
    method: notification ? 'POST' : 'GET',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: notification ? JSON.stringify(notification) : null,
    redirect: 'error',
    signal: AbortSignal.timeout(45000),
  });
  if (!response.ok) fail('GENERATOR_HTTP_REJECTED', 503);
  return response.json() as Promise<unknown>;
}
export async function pollGenerator(client: Sql) {
  requireGeneratorEnabled();
  await requireGeneratorMain(client);
  // An ambiguous HTTP failure is recovered from the durable execution first.
  // Live/terminal executions are never regenerated by transport recovery.
  const rows = await client<
    { id: string; input_digest: string; generation: number; dispatch_id: string }[]
  >`
    SELECT r.id,r.input_digest,d.id AS dispatch_id,d.generation FROM analysis_requests r
    JOIN LATERAL(SELECT id,generation FROM analysis_request_dispatches WHERE request_id=r.id ORDER BY generation DESC LIMIT 1)d ON true
    JOIN analytics_outbox o ON o.entity_id=r.id AND o.event_name='analysis.requested'
    JOIN outbox_deliveries delivery ON delivery.outbox_id=o.id AND delivery.consumer='irt_compute'
    LEFT JOIN irt_compute.compute_executions e ON e.dispatch_id=d.id
    WHERE r.request_type='GENERATE_VARIANTS' AND r.status IN ('PENDING','RUNNING')
    AND (delivery.retry_at IS NULL OR delivery.retry_at<=clock_timestamp())
    AND (e.id IS NULL OR (e.status='RUNNING' AND e.lease_expires_at<=clock_timestamp()))
    ORDER BY r.created_at,r.id LIMIT 10`;
  let notified = 0,
    failed = 0;
  for (const r of rows) {
    const notification: ComputeNotificationV3 = {
      contractVersion: 3,
      requestId: r.id,
      inputDigest: r.input_digest,
      dispatchGeneration: r.generation,
    };
    let code: string | null = null;
    try {
      await generatorHttp('/api/v1/compute/execute', notification);
      notified++;
    } catch {
      const [execution] = await client<
        { status: string }[]
      >`SELECT status FROM irt_compute.compute_executions WHERE dispatch_id=${r.dispatch_id}`;
      if (!execution) {
        code = 'GENERATOR_NOTIFICATION_FAILED';
        failed++;
      }
    }
    await client`UPDATE outbox_deliveries delivery SET attempts=attempts+1,
      delivered_at=CASE WHEN ${code}::text IS NULL THEN clock_timestamp() ELSE delivered_at END,
      retry_at=clock_timestamp()+interval '30 seconds',failure_code=${code}
      FROM analytics_outbox o WHERE o.id=delivery.outbox_id AND o.entity_id=${r.id} AND delivery.consumer='irt_compute'
      AND (SELECT max(generation) FROM analysis_request_dispatches WHERE request_id=${r.id})=${r.generation}`;
  }
  return { notified, failed };
}
