// Generated from pvp-events.schema.json. Do not edit by hand.

export type PvpSnapshotDto = { "matchId": string; "roomCode": string; "creatorStudentId": string; "difficulty": "easy" | "medium" | "hard"; "status": "WAITING" | "READY" | "RUNNING" | "FINISHED" | "CANCELLED"; "serverTime": string; "isDemo": boolean; "participantActive"?: boolean; "expiresAt"?: string | null; "recordEligible": boolean; "endReason": string | null; "players": (PvpPlayerDto)[]; "question": PvpQuestionDto | null; };

export type PvpPlayerDto = { "studentId": string; "displayName": string; "slot": number; "ready": boolean; "connectionStatus": string; "reconnectDeadlineAt": string | null; "points": number; "result": string | null; };

export type StudentPeerDto = { "studentId": string; "displayName": string; };

export type PvpQuestionDto = { "id": string; "order": number; "stem": string; "options": (OptionDto)[]; "deadlineAt": string; "durationSeconds": number; "answered": boolean; "selectedOptionId": string | null; };

export type OptionDto = { "id": string; "text": string; };

export type Problem = { "status": number; "code": string; "detail": string; };

export type Acknowledgement = { "ok": true; "state": PvpSnapshotDto | null; "response": { "inviteId": string; } | null; } | { "ok": false; "error": Problem; };

export type PvpEnvelope = { "event": "room:create"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "difficulty": "easy" | "medium" | "hard"; }; } | { "event": "room:join"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "roomCode": string; }; } | { "event": "player:ready"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "matchId": string; }; } | { "event": "answer:submit"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "matchId": string; "questionId": string; "optionId": string | null; }; } | { "event": "match:reconnect"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "matchId": string; }; } | { "event": "room:leave"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "matchId": string; }; } | { "event": "room:cancel"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "matchId": string; }; } | { "event": "invitation:send"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "matchId": string; "recipientStudentId": string; }; } | { "event": "invitation:respond"; "eventVersion": "1"; "requestId": string; "sentAt": string; "payload": { "inviteId": string; "accept": boolean; }; } | { "event": "room:state"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": PvpSnapshotDto; } | { "event": "match:started"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": PvpSnapshotDto; } | { "event": "question:started"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": PvpSnapshotDto; } | { "event": "match:completed"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": PvpSnapshotDto; } | { "event": "match:forfeited"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": PvpSnapshotDto; } | { "event": "match:cancelled"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": PvpSnapshotDto; } | { "event": "question:resolved"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": { "matchId": string; "questionId": string; }; } | { "event": "player:disconnected"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": { "matchId": string; "studentId": string; }; } | { "event": "invitation:received"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": { "inviteId": string; }; } | { "event": "command:acknowledged"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": Acknowledgement; } | { "event": "answer:acknowledged"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": Acknowledgement; } | { "event": "room:error"; "eventVersion": "1"; "requestId": string | null; "sentAt": string; "payload": Problem; };
